// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyI7dqoYXyMj023MiNhUvlw_aHdrUfow',
    appId: '1:765587652218:web:486ebd801938d94f2645c3',
    messagingSenderId: '765587652218',
    projectId: 'flutter-firebase-masterc-b5089',
    authDomain: 'flutter-firebase-masterc-b5089.firebaseapp.com',
    storageBucket: 'flutter-firebase-masterc-b5089.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0H-Ygt700XsgptklL-pHeal-9CyVAcc',
    appId: '1:765587652218:android:c28a9e37f72a51f52645c3',
    messagingSenderId: '765587652218',
    projectId: 'flutter-firebase-masterc-b5089',
    storageBucket: 'flutter-firebase-masterc-b5089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwHXUr8f7DO50GCqj-9BIRFKl1pl7fiw8',
    appId: '1:765587652218:ios:3d9e233277a5708a2645c3',
    messagingSenderId: '765587652218',
    projectId: 'flutter-firebase-masterc-b5089',
    storageBucket: 'flutter-firebase-masterc-b5089.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwHXUr8f7DO50GCqj-9BIRFKl1pl7fiw8',
    appId: '1:765587652218:ios:3d9e233277a5708a2645c3',
    messagingSenderId: '765587652218',
    projectId: 'flutter-firebase-masterc-b5089',
    storageBucket: 'flutter-firebase-masterc-b5089.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyI7dqoYXyMj023MiNhUvlw_aHdrUfow',
    appId: '1:765587652218:web:558ed997c8fbf7832645c3',
    messagingSenderId: '765587652218',
    projectId: 'flutter-firebase-masterc-b5089',
    authDomain: 'flutter-firebase-masterc-b5089.firebaseapp.com',
    storageBucket: 'flutter-firebase-masterc-b5089.firebasestorage.app',
  );
}
